# Generated by Django 5.2.3 on 2025-08-19 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutClub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("about", models.TextField(max_length=16384)),
            ],
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="", max_length=32)),
                ("author", models.CharField(max_length=32)),
                ("description", models.CharField(max_length=1024)),
                ("content", models.TextField(max_length=16384)),
                (
                    "blog_image",
                    models.ImageField(default="", upload_to="gallery/blogs/"),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("astronomy", "Astronomy"),
                            ("physics", "Physics"),
                            ("space_missions", "Space Missions"),
                            ("people", "People"),
                            ("astropoetry", "Astropoetry"),
                            ("astrofiction", "Astrofiction"),
                            ("book_reviews", "Book Reviews"),
                            ("mythology", "Mythology"),
                            ("philosophy", "Philosophy"),
                        ],
                        default="astronomy",
                        max_length=32,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CategoryCover",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("night_sky_stars", "Night Sky Stars"),
                            ("nebula", "Nebula"),
                            ("stargazing", "Stargazing"),
                            ("planet_photography", "Planet Photography"),
                            ("moon_photography", "Moon Photography"),
                            ("star_clusters", "Star Clusters"),
                            ("galaxy_photography", "Galaxy Photography"),
                            ("eclipse_photography", "Eclipse Photography"),
                        ],
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(upload_to="gallery/category_covers/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("description", models.TextField(max_length=256)),
                ("date", models.DateTimeField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="gallery/events/"
                    ),
                ),
                ("status", models.CharField(max_length=8)),
                ("location", models.TextField(max_length=128)),
                ("event_type", models.CharField(max_length=32)),
                ("registration_link", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="GalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="gallery/others_photos/")),
                ("title", models.CharField(max_length=32)),
                ("description", models.TextField(max_length=128)),
                ("photographer_name", models.CharField(max_length=64)),
                (
                    "photo_type",
                    models.CharField(
                        choices=[
                            ("night_sky_stars", "Night Sky Stars"),
                            ("nebula", "Nebula"),
                            ("stargazing", "Stargazing"),
                            ("planet_photography", "Planet Photography"),
                            ("moon_photography", "Moon Photography"),
                            ("star_clusters", "Star Clusters"),
                            ("galaxy_photography", "Galaxy Photography"),
                            ("eclipse_photography", "Eclipse Photography"),
                        ],
                        max_length=32,
                    ),
                ),
                ("date_uploaded", models.DateTimeField(blank=True, null=True)),
                ("approved", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("role", models.CharField(max_length=64)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="gallery/team/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="", max_length=32)),
                ("description", models.TextField(default="")),
                ("references", models.CharField(default="", max_length=32)),
                (
                    "research_paper",
                    models.FileField(blank=True, null=True, upload_to="papers/"),
                ),
                ("status", models.BooleanField(default=True)),
                (
                    "cover_page",
                    models.ImageField(
                        blank=True, null=True, upload_to="gallery/project_covers/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Recruitment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recruitment_status", models.BooleanField(default=False)),
                ("recruitment_description", models.TextField(max_length=256)),
                ("closing_date", models.DateTimeField(null=True)),
                ("form_link", models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Contributor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "project_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contributors",
                        to="website.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="gallery/project_images/"
                    ),
                ),
                (
                    "project_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_images",
                        to="website.project",
                    ),
                ),
            ],
        ),
    ]
