# Generated by Django 5.2.3 on 2025-08-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="author",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="blog",
            name="title",
            field=models.CharField(default="", max_length=128),
        ),
    ]
