# Generated by Django 5.2.3 on 2025-08-21 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_alter_event_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
    ]
