# Generated by Django 5.2.5 on 2025-10-30 15:22

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0005_alter_event_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(max_length=16384),
        ),
    ]
